server.port=8080
spring.application.name=gateway-demo
eureka.client.service-url.defaultZone=http://eureka-demo:8761/eureka/


spring.cloud.gateway.server.webflux.routes[0].id=WELCOME-DEMO
spring.cloud.gateway.server.webflux.routes[0].uri=lb://WELCOME-DEMO
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/welcome/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webflux.routes[0].filters[1]=AddRequestHeader=X-Request-red, blue
spring.cloud.gateway.server.webflux.routes[0].filters[2]=AddResponseHeader=X-Response-Red, Blue


management.endpoints.web.exposure.include=*
management.endpoint.gateway.access=READ_ONLY


# How often client sends heartbeat (default: 30 seconds)
eureka.instance.lease-renewal-interval-in-seconds=5
#how long instance can alive with heart bean or dead time length (default: 90 seconds)
eureka.instance.lease-expiration-duration-in-seconds=10