
server.port=8081
spring.application.name=welcome-demo
spring.config.import=optional:configserver:http://config-server:8887
eureka.client.service-url.defaultZone=http://eureka-demo-amir87-tech-dev.apps.rm1.0a51.p1.openshiftapps.com/eureka/


# How often client sends heartbeat (default: 30 seconds)
eureka.instance.lease-renewal-interval-in-seconds=5
#how long instance can alive with heart bean or dead time length (default: 90 seconds)
eureka.instance.lease-expiration-duration-in-seconds=10

management.endpoints.web.exposure.include=*

eureka.instance.prefer-ip-address=true

#eureka.instance.hostname=welcome-demo




